config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, :only => [:new]
    resources :friendships, :only => [:create, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :secrets, :only => [:create]


  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id


end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  validates :author_id, :recipient_id, :title, :presence => true

  has_many :secret_taggings
  has_many :tags, through: :secret_taggings, source: :tag

end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id
  validates :secret_id, :tag_id, presence: true

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title
  validates :title, presence: true


  has_many :secret_taggings
  has_many :secrets, through: :secret_taggings, source: :secret

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    sleep(1)
    @friendship = Friendship.new

    @friendship.out_friend_id = current_user.id
    @friendship.in_friend_id = params[:user_id]

    @friendship.save!

    respond_to do |format|
      format.html { redirect_to users_url }

      format.json { render :json => @friendship}
    end

  end

  def destroy
    @friendship = Friendship.find_by_out_friend_id_and_in_friend_id(current_user.id,params[:user_id]);

    # if
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to users_url }

      format.json { render :json => @friendship}
    end

    # else
    #   flash[:errors] = @friendship.errors.full_messages
    #   redirect_to :back
    # end
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def new

    @secret = Secret.new


    # @secret.recipient_id = params[:user_id]

  end

  def create
    secret = Secret.new(params[:secret])

    secret.author_id = current_user.id

    secret.tag_ids = params[:tag][:tag_ids]

    if secret.save

      respond_to do |format|
        format.html { redirect_to users_url }

        format.json { render :json => secret}
      end

    else
      flash.now[:errors] = secret.errors.full_messages
      render :json => params
      # render :new
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

  def can_friend?(out_friend_id, in_friend_id)
    !Friendship.exists?({out_friend_id: out_friend_id, in_friend_id: in_friend_id}) &&
    in_friend_id != current_user.id
  end

  def can_unfriend(out_friend_id, in_friend_id)
    return Friendship.find_by_out_friend_id_and_in_friend_id(out_friend_id,in_friend_id)


  end
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_add_friend.html.erb
<form class="friend" data-infriend="<%= in_friend_id %>">
  <input type="submit" value="Add friend">
</form>

app/views/friendships/_remove_friend.html.erb
<form class="unfriend" data-infriend="<%= in_friend_id %>" data-friendshipid="<%= friendship_id %>">
  <input type="submit" value="Remove friend">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
  .hidden {
    display: none;
  }

  .friend {
    display: block;
  }

  .unfriend {
    display: none;
  }

  .is-friends > .friend {
    display: none;
  }

  .is-friends > .unfriend {
    display: block;
  }

  </style>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= params %>
  <br>


  <%= flash[:errors] %>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form action="<%= secrets_url %>" method="post" class="new_secret">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">

  <label for="title">Title</label>
  <input type="text" name="secret[title]" value="" id="title">


  <div id="tags_go_here">

  </div>

  <input type="hidden" name="secret[recipient_id]" value="<%= recipient_id %>">
  <input type="submit" name="" value="Submit" id="">
</form>

  <a href="#" id="addmoretags">Add More Tags</a>





  <script type="application/json" id="bootstrapped_tags">
    {"tags": <%= Tag.all.to_json.html_safe %>}
  </script>



<script type="text/template" id="tags_template">
  <select id="tag_select" name="tag[tag_ids][]">
  <%% _(tags).each(function(tag) {  %>
    <option value="<%%= tag.id %>"> <%%= tag.title %> </option>
  <%% }); %>

  </select>
</script>



<script type="application/javascript">
  var tags = JSON.parse($('#bootstrapped_tags').html()).tags;
  // templateCode is a string with the contents of the script tag.
  var templateCode = $("#tags_template").html();

  // compile the template code to a JavaScript function
  var templateFn = _.template(templateCode);

  // evaluate the template; producing html
  var renderedContent = templateFn({
    // variables in here are available inside the template
    tags: tags
  });

  // finally, we can inject the content
  function addSecretTagSelect() {
    $("#tags_go_here").append(renderedContent);
  }

  //addSecretTagSelect();

  $(document).ready(function() {
    $('#addmoretags').on('click', function() {
      event.preventDefault();
      addSecretTagSelect();
    })
  })

</script>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">

  <label for="title">Title</label>
  <input type="text" name="secret[title]" value="" id="title">

  <input type="hidden" name="secret[recipient_id]" value="<%= params[:user_id] %>">

  <input type="submit" name="" value="Submit" id="">


</form>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
<% next if user.id == current_user.id %>
<li>
  <%= user.username %> |

  <% friendship_obj = can_unfriend(current_user.id, user.id)  %>

  <div class="friend-buttons <%= "is-friends" unless can_friend?(current_user.id, user.id) %> ">
    <form class="friend" data-infriend="<%= user.id %>">
      <input type="submit" value="Add friend">
    </form>

    <form class="unfriend" data-infriend="<%= user.id %>" data-friendshipid="<%= friendship_obj.id if friendship_obj %>">
      <input type="submit" value="Remove friend">
    </form>
  </div>

</li>

<% end %>

</ul>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<script type="text/javascript">
$(document).ready(function() {
  $('.new_secret').on('submit', function(event) {
    event.preventDefault();
    var formData = $(this).serialize();
    var that = this;

    var req = $.ajax({
      url: "/secrets.json", //make sure in .JSON
      data: formData,
      type:'post',
      success: function(resp) {
        console.log("Great job");
        console.log(resp);
        $("#title").val(""); //clears input form
        $('.user_secrets').prepend("<li>" + resp.title + "</li>")
      },
    });

  })
});

</script>

<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul class="user_secrets">
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>


<%= render "secrets/form", recipient_id: @user.id %>